
# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr, here

      - name: Install Package
        run: |
          R CMD INSTALL --install-tests .
      - name: Test coverage
        run: covr::codecov()
        # run: |
        #  Sys.setenv("CODECOV_TOKEN" = "${{ secrets.CODECOV_TOKEN }}")
        #  covr::codecov(coverage = covr::package_coverage(here::here(), type = "tests", quiet = FALSE, line_exclusions = list("tests/spelling.R"))) #line_exclusions = list("R/utils-msg_helpers.R")))
        shell: Rscript {0}
